#ifndef FT_MALCOLM_FT_STATUS_H
#define FT_MALCOLM_FT_STATUS_H
enum ft_status {
    SUCCESS,
    INVALID_ARGS,
    CANT_OPEN_SOCKET,
    CANT_GET_NETWORK_INTERFACES,
    CANT_RECEIVE_MESSAGE,
    CANT_SEND_ARP_RESPONSE
};
#endif //FT_MALCOLM_FT_STATUS_H
